### ISSUE TITLE
Get sample API data to Front-end team

### ISSUE THREAD

**Issue by clarkdowner** [freudianantelopes/freudianantelopes#5]
Need example responses for api requests to: Facebook, Instagram, and Twitter

**Comment by clarkdowner** [comment]
example twitter response: 

[ { profilePic: 'https://pbs.twimg.com/profile_images/378800000188901950/de1a11df6c63a9c05d0a7a66ccaa0ff2_normal.jpeg',
    postContent: '@maro254 I\'m bummed, I think the pt will be much less exciting now (except the first of each year)',
    timeStamp: 'Wed Oct 19 21:41:27 +0000 2016',
    service: 'Twitter',
    linkToPost: 'https://twitter.com/samdsherman/status/788857619767173120',
    retweetCount: 0,
    likes: 0 },
  { profilePic: 'https://pbs.twimg.com/profile_images/378800000188901950/de1a11df6c63a9c05d0a7a66ccaa0ff2_normal.jpeg',
    postContent: '@LanielD it\'s kind of a freeroll though since if you die, you can\'t use the money anyway',
    timeStamp: 'Wed Oct 19 02:49:27 +0000 2016',
    service: 'Twitter',
    linkToPost: 'https://twitter.com/samdsherman/status/788572743084093440',
    retweetCount: 0,
    likes: 1 },
  { profilePic: 'https://pbs.twimg.com/profile_images/378800000188901950/de1a11df6c63a9c05d0a7a66ccaa0ff2_normal.jpeg',
    postContent: '@bsweitz123 this is why I never go outside',
    timeStamp: 'Tue Oct 18 20:04:51 +0000 2016',
    service: 'Twitter',
    linkToPost: 'https://twitter.com/samdsherman/status/788470922420232192',
    retweetCount: 0,
    likes: 1 },
  { profilePic: 'https://pbs.twimg.com/profile_images/737761364941242368/Vbckuze3_normal.jpg',
    postContent: 'I know some really cool people. And they made an amazing Album. No matter your taste in music, #GeorgicaPon... https://t.co/nSwb65x2W2',
    timeStamp: 'Mon Oct 17 17:29:30 +0000 2016',
    service: 'Twitter',
    linkToPost: 'https://twitter.com/StephenCurry30/status/788069440189440004',
    retweetCount: 668,
    likes: 4621 },
  { profilePic: 'https://pbs.twimg.com/profile_images/737761364941242368/Vbckuze3_normal.jpg',
    postContent: 'Great win in Vegas tonight! And even better that @notthefakeSVP can help us celebrate in style!… https://t.co/qnCRVETg3d',
    timeStamp: 'Sun Oct 16 06:44:53 +0000 2016',
    service: 'Twitter',
    linkToPost: 'https://twitter.com/StephenCurry30/status/787544827671875584',
    retweetCount: 968,
    likes: 8002 },
  { profilePic: 'https://pbs.twimg.com/profile_images/737761364941242368/Vbckuze3_normal.jpg',
    postContent: 'Guess you can call that a solid game by @PMcCaw0 hitting shots to send us to OT AND win the game! #dubnation',
    timeStamp: 'Sat Oct 15 04:47:01 +0000 2016',
    service: 'Twitter',
    linkToPost: 'https://twitter.com/StephenCurry30/status/787152776954388481',
    retweetCount: 2560,
    likes: 9998 } ]

**Comment by clarkdowner** [comment]
example twitter response: 

[ { profilePic: 'https://pbs.twimg.com/profile_images/378800000188901950/de1a11df6c63a9c05d0a7a66ccaa0ff2_normal.jpeg',
    postContent: '@maro254 I\'m bummed, I think the pt will be much less exciting now (except the first of each year)',
    groupMemberName: '<user defined name for group member>',
    timeStamp: 'Wed Oct 19 21:41:27 +0000 2016',
    service: 'Twitter',
    linkToPost: 'https://twitter.com/samdsherman/status/788857619767173120',
    retweetCount: 0,
    likes: 0 },
  { profilePic: 'https://pbs.twimg.com/profile_images/378800000188901950/de1a11df6c63a9c05d0a7a66ccaa0ff2_normal.jpeg',
    postContent: '@LanielD it\'s kind of a freeroll though since if you die, you can\'t use the money anyway',
    groupMemberName: '<user defined name for group member>',
    timeStamp: 'Wed Oct 19 02:49:27 +0000 2016',
    service: 'Twitter',
    linkToPost: 'https://twitter.com/samdsherman/status/788572743084093440',
    retweetCount: 0,
    likes: 1 },
  { profilePic: 'https://pbs.twimg.com/profile_images/378800000188901950/de1a11df6c63a9c05d0a7a66ccaa0ff2_normal.jpeg',
    postContent: '@bsweitz123 this is why I never go outside',
    groupMemberName: '<user defined name for group member>',
    timeStamp: 'Tue Oct 18 20:04:51 +0000 2016',
    service: 'Twitter',
    linkToPost: 'https://twitter.com/samdsherman/status/788470922420232192',
    retweetCount: 0,
    likes: 1 },
  { profilePic: 'https://pbs.twimg.com/profile_images/737761364941242368/Vbckuze3_normal.jpg',
    postContent: 'I know some really cool people. And they made an amazing Album. No matter your taste in music, #GeorgicaPon... https://t.co/nSwb65x2W2',
    groupMemberName: '<user defined name for group member>',
    timeStamp: 'Mon Oct 17 17:29:30 +0000 2016',
    service: 'Twitter',
    linkToPost: 'https://twitter.com/StephenCurry30/status/788069440189440004',
    retweetCount: 668,
    likes: 4621 },
  { profilePic: 'https://pbs.twimg.com/profile_images/737761364941242368/Vbckuze3_normal.jpg',
    postContent: 'Great win in Vegas tonight! And even better that @notthefakeSVP can help us celebrate in style!… https://t.co/qnCRVETg3d',
    groupMemberName: '<user defined name for group member>',
    timeStamp: 'Sun Oct 16 06:44:53 +0000 2016',
    service: 'Twitter',
    linkToPost: 'https://twitter.com/StephenCurry30/status/787544827671875584',
    retweetCount: 968,
    likes: 8002 },
  { profilePic: 'https://pbs.twimg.com/profile_images/737761364941242368/Vbckuze3_normal.jpg',
    postContent: 'Guess you can call that a solid game by @PMcCaw0 hitting shots to send us to OT AND win the game! #dubnation',
    groupMemberName: '<user defined name for group member>',
    timeStamp: 'Sat Oct 15 04:47:01 +0000 2016',
    service: 'Twitter',
    linkToPost: 'https://twitter.com/StephenCurry30/status/787152776954388481',
    retweetCount: 2560,
    likes: 9998 } ]

**Comment by WillStockman13** [comment]
instgram api callback:

[ { profilePic: 'https://scontent-sjc2-1.cdninstagram.com/t51.2885-15/e15/11377858_993781180655250_1652239831_n.jpg?ig_cache_key=MTA0NjczMTIwNzY1ODI1NTU3Mw%3D%3D.2',
    postContent: 'Wazzup',
    groupMember: 'jamesstockman14',
    timeStamp: 1439000105,
    service: 'Instagram',
    linkToPost: 'https://www.instagram.com/p/6GvHzPyTTV/?taken-by=jamesstockman14',
    favoriteCount: 73,
    comments: 3 },
  { profilePic: 'https://scontent-sjc2-1.cdninstagram.com/t51.2885-15/e15/11420712_520588338093804_756758009_n.jpg?ig_cache_key=MTAzMjkxMzIwMTAyMjk3MzM2OA%3D%3D.2',
    postContent: 'Even though we weren\'t on a cruise this time, it\'s always a treat spending time with my favorite travel partner🌇',
    groupMember: 'jamesstockman14',
    timeStamp: 1437352870,
    service: 'Instagram',
    linkToPost: 'https://www.instagram.com/p/5VpRVuyTW4/?taken-by=jamesstockman14',
    favoriteCount: 86,
    comments: 5 },
  { profilePic: 'https://scontent-sjc2-1.cdninstagram.com/t51.2885-15/e15/10899012_811824435522514_1308559690_n.jpg?ig_cache_key=ODkzNzA1ODgzMzQyMTU3NjYz.2',
    postContent: 'Can\'t beat Athens🐶',
    groupMember: 'jamesstockman14',
    timeStamp: 1420758065,
    service: 'Instagram',
    linkToPost: 'https://www.instagram.com/p/xnFMQOSTdf/?taken-by=jamesstockman14',
    favoriteCount: 70,
    comments: 5 },
  { profilePic: 'https://scontent-sjc2-1.cdninstagram.com/t51.2885-15/e15/10895365_331222457082728_2044663225_n.jpg?ig_cache_key=ODg4NTU4OTg4MzYxODA3MTgz.2',
    postContent: 'The Stockman family Christmas Break🎄',
    groupMember: 'jamesstockman14',
    timeStamp: 1420144507,
    service: 'Instagram',
    linkToPost: 'https://www.instagram.com/p/xUy7EvSTVP/?taken-by=jamesstockman14',
    favoriteCount: 75,
    comments: 0 },
  { profilePic: 'https://scontent-sjc2-1.cdninstagram.com/t51.2885-15/e15/10831872_1517823131833767_379375788_n.jpg?ig_cache_key=ODc4NTEyMzM3MTY5NDk1NjE1.2',
    postContent: 'Road-tripping USA🇺🇸',
    groupMember: 'jamesstockman14',
    timeStamp: 1418946853,
    service: 'Instagram',
    linkToPost: 'https://www.instagram.com/p/wxGlDryTY_/?taken-by=jamesstockman14',
    favoriteCount: 90,
    comments: 2 },
  { profilePic: 'https://scontent-sjc2-1.cdninstagram.com/t51.2885-15/e15/10864677_470788693062021_360480991_n.jpg?ig_cache_key=ODc3NzIwNTQ4MjU0NzU4MTM3.2',
    postContent: 'Glad to see that the US and Cuba are figuring things out and making a much needed change by releasing prisoners on both sides. I\'m hopeful that this is the beginning of a larger change between these countries.',
    groupMember: 'jamesstockman14',
    timeStamp: 1418852464,
    service: 'Instagram',
    linkToPost: 'https://www.instagram.com/p/wuSjAyyTT5/?taken-by=jamesstockman14',
    favoriteCount: 65,
    comments: 0 },
  { profilePic: 'https://scontent-sjc2-1.cdninstagram.com/t51.2885-15/e15/915607_737278479699846_400243924_n.jpg?ig_cache_key=ODc2MjM2ODEzMDgwNTQwNDEw.2',
    postContent: 'First stop of the road trip: Bourbon Street #GAtoWA',
    groupMember: 'jamesstockman14',
    timeStamp: 1418675589,
    service: 'Instagram',
    linkToPost: 'https://www.instagram.com/p/wpBL0uyTT6/?taken-by=jamesstockman14',
    favoriteCount: 83,
    comments: 0 },
  { profilePic: 'https://scontent-sjc2-1.cdninstagram.com/t51.2885-15/e15/10852791_418386764994307_1485324387_n.jpg?ig_cache_key=ODcyNjY0OTE3NTIxMDIwMDcz.2',
    postContent: 'Finally made it back to America after one incredible start to freshman year🚢⚓️🇺🇸',
    groupMember: 'jamesstockman14',
    timeStamp: 1418249786,
    service: 'Instagram',
    linkToPost: 'https://www.instagram.com/p/wcVB5wyTSp/?taken-by=jamesstockman14',
    favoriteCount: 111,
    comments: 2 },
  { profilePic: 'https://scontent-sjc2-1.cdninstagram.com/t51.2885-15/e15/10844179_883415351699083_244599671_n.jpg?ig_cache_key=ODcwOTMwNTgwNzI3NDc3MzUy.2',
    postContent: 'Semester at Sea definitely saved the best for last with Cuba',
    groupMember: 'jamesstockman14',
    timeStamp: 1418043037,
    service: 'Instagram',
    linkToPost: 'https://www.instagram.com/p/wWKr-wSTRo/?taken-by=jamesstockman14',
    favoriteCount: 98,
    comments: 2 },
  { profilePic: 'https://scontent-sjc2-1.cdninstagram.com/t51.2885-15/e15/10013020_755865167826845_1459691151_n.jpg?ig_cache_key=ODYzMzM2MDAyNDkxMDcwMjc0.2',
    postContent: 'Dancing in the rain and karaoke in the streets ☔️🎤',
    groupMember: 'jamesstockman14',
    timeStamp: 1417137693,
    service: 'Instagram',
    linkToPost: 'https://www.instagram.com/p/v7L4UmSTdC/?taken-by=jamesstockman14',
    favoriteCount: 76,
    comments: 2 },
  { profilePic: 'https://scontent-sjc2-1.cdninstagram.com/t51.2885-15/e15/10808680_819994624724189_1515207074_n.jpg?ig_cache_key=ODYwOTQwNjk5NDMxNDE3MjMy.2',
    postContent: 'Throwing it back while I have wifi to the great times I\'ve had with @meganconnelly7 these last few months 🇪🇸🇫🇷🇮🇹',
    groupMember: 'jamesstockman14',
    timeStamp: 1416852150,
    service: 'Instagram',
    linkToPost: 'https://www.instagram.com/p/vyrQEySTWQ/?taken-by=jamesstockman14',
    favoriteCount: 71,
    comments: 3 },
  { profilePic: 'https://scontent-sjc2-1.cdninstagram.com/t51.2885-15/e15/10561033_639563829488169_1769052868_n.jpg?ig_cache_key=ODYwMjE0Mjg0MjcyNjEzMTA5.2',
    postContent: 'Formal Dinning on the MV Explorer 🍴🍷',
    groupMember: 'jamesstockman14',
    timeStamp: 1416765555,
    service: 'Instagram',
    linkToPost: 'https://www.instagram.com/p/vwGFV8yTb1/?taken-by=jamesstockman14',
    favoriteCount: 58,
    comments: 2 } ]
[ { profilePic: 'https://scontent-sjc2-1.cdninstagram.com/t51.2885-15/e15/11377858_993781180655250_1652239831_n.jpg?ig_cache_key=MTA0NjczMTIwNzY1ODI1NTU3Mw%3D%3D.2',
    postContent: 'Wazzup',
    groupMember: 'jamesstockman14',
    timeStamp: 1439000105,
    service: 'Instagram',
    linkToPost: 'https://www.instagram.com/p/6GvHzPyTTV/?taken-by=jamesstockman14',
    favoriteCount: 73,
    comments: 3 },
  { profilePic: 'https://scontent-sjc2-1.cdninstagram.com/t51.2885-15/e15/11420712_520588338093804_756758009_n.jpg?ig_cache_key=MTAzMjkxMzIwMTAyMjk3MzM2OA%3D%3D.2',
    postContent: 'Even though we weren\'t on a cruise this time, it\'s always a treat spending time with my favorite travel partner🌇',
    groupMember: 'jamesstockman14',
    timeStamp: 1437352870,
    service: 'Instagram',
    linkToPost: 'https://www.instagram.com/p/5VpRVuyTW4/?taken-by=jamesstockman14',
    favoriteCount: 86,
    comments: 5 },
  { profilePic: 'https://scontent-sjc2-1.cdninstagram.com/t51.2885-15/e15/10899012_811824435522514_1308559690_n.jpg?ig_cache_key=ODkzNzA1ODgzMzQyMTU3NjYz.2',
    postContent: 'Can\'t beat Athens🐶',
    groupMember: 'jamesstockman14',
    timeStamp: 1420758065,
    service: 'Instagram',
    linkToPost: 'https://www.instagram.com/p/xnFMQOSTdf/?taken-by=jamesstockman14',
    favoriteCount: 70,
    comments: 5 },
  { profilePic: 'https://scontent-sjc2-1.cdninstagram.com/t51.2885-15/e15/10895365_331222457082728_2044663225_n.jpg?ig_cache_key=ODg4NTU4OTg4MzYxODA3MTgz.2',
    postContent: 'The Stockman family Christmas Break🎄',
    groupMember: 'jamesstockman14',
    timeStamp: 1420144507,
    service: 'Instagram',
    linkToPost: 'https://www.instagram.com/p/xUy7EvSTVP/?taken-by=jamesstockman14',
    favoriteCount: 75,
    comments: 0 },
  { profilePic: 'https://scontent-sjc2-1.cdninstagram.com/t51.2885-15/e15/10831872_1517823131833767_379375788_n.jpg?ig_cache_key=ODc4NTEyMzM3MTY5NDk1NjE1.2',
    postContent: 'Road-tripping USA🇺🇸',
    groupMember: 'jamesstockman14',
    timeStamp: 1418946853,
    service: 'Instagram',
    linkToPost: 'https://www.instagram.com/p/wxGlDryTY_/?taken-by=jamesstockman14',
    favoriteCount: 90,
    comments: 2 },
  { profilePic: 'https://scontent-sjc2-1.cdninstagram.com/t51.2885-15/e15/10864677_470788693062021_360480991_n.jpg?ig_cache_key=ODc3NzIwNTQ4MjU0NzU4MTM3.2',
    postContent: 'Glad to see that the US and Cuba are figuring things out and making a much needed change by releasing prisoners on both sides. I\'m hopeful that this is the beginning of a larger change between these countries.',
    groupMember: 'jamesstockman14',
    timeStamp: 1418852464,
    service: 'Instagram',
    linkToPost: 'https://www.instagram.com/p/wuSjAyyTT5/?taken-by=jamesstockman14',
    favoriteCount: 65,
    comments: 0 },
  { profilePic: 'https://scontent-sjc2-1.cdninstagram.com/t51.2885-15/e15/915607_737278479699846_400243924_n.jpg?ig_cache_key=ODc2MjM2ODEzMDgwNTQwNDEw.2',
    postContent: 'First stop of the road trip: Bourbon Street #GAtoWA',
    groupMember: 'jamesstockman14',
    timeStamp: 1418675589,
    service: 'Instagram',
    linkToPost: 'https://www.instagram.com/p/wpBL0uyTT6/?taken-by=jamesstockman14',
    favoriteCount: 83,
    comments: 0 },
  { profilePic: 'https://scontent-sjc2-1.cdninstagram.com/t51.2885-15/e15/10852791_418386764994307_1485324387_n.jpg?ig_cache_key=ODcyNjY0OTE3NTIxMDIwMDcz.2',
    postContent: 'Finally made it back to America after one incredible start to freshman year🚢⚓️🇺🇸',
    groupMember: 'jamesstockman14',
    timeStamp: 1418249786,
    service: 'Instagram',
    linkToPost: 'https://www.instagram.com/p/wcVB5wyTSp/?taken-by=jamesstockman14',
    favoriteCount: 111,
    comments: 2 },
  { profilePic: 'https://scontent-sjc2-1.cdninstagram.com/t51.2885-15/e15/10844179_883415351699083_244599671_n.jpg?ig_cache_key=ODcwOTMwNTgwNzI3NDc3MzUy.2',
    postContent: 'Semester at Sea definitely saved the best for last with Cuba',
    groupMember: 'jamesstockman14',
    timeStamp: 1418043037,
    service: 'Instagram',
    linkToPost: 'https://www.instagram.com/p/wWKr-wSTRo/?taken-by=jamesstockman14',
    favoriteCount: 98,
    comments: 2 },
  { profilePic: 'https://scontent-sjc2-1.cdninstagram.com/t51.2885-15/e15/10013020_755865167826845_1459691151_n.jpg?ig_cache_key=ODYzMzM2MDAyNDkxMDcwMjc0.2',
    postContent: 'Dancing in the rain and karaoke in the streets ☔️🎤',
    groupMember: 'jamesstockman14',
    timeStamp: 1417137693,
    service: 'Instagram',
    linkToPost: 'https://www.instagram.com/p/v7L4UmSTdC/?taken-by=jamesstockman14',
    favoriteCount: 76,
    comments: 2 },
  { profilePic: 'https://scontent-sjc2-1.cdninstagram.com/t51.2885-15/e15/10808680_819994624724189_1515207074_n.jpg?ig_cache_key=ODYwOTQwNjk5NDMxNDE3MjMy.2',
    postContent: 'Throwing it back while I have wifi to the great times I\'ve had with @meganconnelly7 these last few months 🇪🇸🇫🇷🇮🇹',
    groupMember: 'jamesstockman14',
    timeStamp: 1416852150,
    service: 'Instagram',
    linkToPost: 'https://www.instagram.com/p/vyrQEySTWQ/?taken-by=jamesstockman14',
    favoriteCount: 71,
    comments: 3 },
  { profilePic: 'https://scontent-sjc2-1.cdninstagram.com/t51.2885-15/e15/10561033_639563829488169_1769052868_n.jpg?ig_cache_key=ODYwMjE0Mjg0MjcyNjEzMTA5.2',
    postContent: 'Formal Dinning on the MV Explorer 🍴🍷',
    groupMember: 'jamesstockman14',
    timeStamp: 1416765555,
    service: 'Instagram',
    linkToPost: 'https://www.instagram.com/p/vwGFV8yTb1/?taken-by=jamesstockman14',
    favoriteCount: 58,
    comments: 2 } ]

**Comment by clarkdowner** [comment]
need to format timestamp on backend to a consistant format
